name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  train:
    runs-on: ubuntu-latest

    outputs:
      mse: ${{ steps.get_metrics.outputs.mse }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model
      run: python scripts/train.py

    - name: Read metrics
      id: get_metrics
      run: |
        MSE=$(python -c "import json; print(json.load(open('output/results.json'))['MSE'])")
        echo "mse=$MSE" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          model.pkl
          output/results.json


  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: .

    - name: Print metric
      run: echo "MSE is ${{ needs.train.outputs.mse }}"

    # ❗ SIMPLE CONDITION (for lab demo)
    - name: Check improvement
      id: check
      run: |
        if (( $(echo "${{ needs.train.outputs.mse }} < 0.6" | bc -l) )); then
          echo "improved=true" >> $GITHUB_OUTPUT
        else
          echo "improved=false" >> $GITHUB_OUTPUT
        fi

    - name: Stop if not improved
      if: steps.check.outputs.improved == 'false'
      run: echo "<YOUR_ROLL_NO>----Metric did not improve"

    - name: Login to DockerHub
      if: steps.check.outputs.improved == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      if: steps.check.outputs.improved == 'true'
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wine-api:latest .

    - name: Push Docker Image
      if: steps.check.outputs.improved == 'true'
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wine-api:latest